services:
  web:
    build: .
    container_name: php-apache
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres
    env_file:
      - ./html/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - ./html/.env
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
